openapi: 3.0.3
info:
  version: '1.0.0'
  title: 'Enkudo DSP Common Data Types'
  description: |
    Common Data Types for Service Based Interfaces.


paths: {}
components:
  schemas:
#
# Common Data Types for  Generic usage definitiones 
#

#
# COMMON SIMPLE DATA TYPES
#
    type:
      description: 'OTP type'
      enum:
        - numeric
        - alphanumeric
    channel:
      description: 'OTP delivery channel'
      enum:
        - sms
        - ussdb
        - web
    offerState:
      description: ''
      enum:
        - active
        - suspended
        - inactive
    serviceNotificationType:
      description: ''
      enum:
        - subscribed
        - unsubscribed
        - reactivated
        - suspended
        - notrenewed
    msisdn:
      description: 'MSISDN of the customer (subscriber)'
      type: string
      maxLength: 20
      pattern: '^[0-9]$'
    trxid:
      description: | 
        'Unique transaction ID within the carrier system
        @@@ It would be better if this can be RFC 4122 uuid'
      type: string
      pattern: '^[a-zA-Z0-9]{1,50}$'
    subscriptionId: 
      description: ''
      type: string 
      format: uuid
    serviceId: 
      type: string
      format: uuid
    service:
      type: object
      properties:
        serviceId:
          $ref: '#/components/schemas/serviceId'
        serviceName:
          type: string        
#
# REQUEST BODIES
#
    AuthCodeRequestBody:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/type' 
        length: 
          description: 'Length of the generated Auth Code'
          type: integer
          format: int32
        template:
          description: 'Template Message that is defined at the OTP module'
          type: string
        sender:
          description: 'Sender address of the  AuthCode SMS'
          type: string      
          maxLength: 1024
        target:
          description: 'Recipient address that requested the Auth Code'
          type: string
          maxLength: 1024
      required:
        - target
    SubscribeRequestBody:
      type: object
      properties:
        Transactiond:
          $ref: '#/components/schemas/trxid'
        Channel:
          $ref: '#/components/schemas/channel'
        msisdn:
          $ref: '#/components/schemas/msisdn'
        offer:
          type: string
        subStateChangeNotificationUri:
          description: | 
            'Callback API to inform Enkudo Subscription service about subscriber state change'
          type: string
      required:
        - Transactiond
        - msisdn
    UnsubscribeRequestBody:
      type: object
      properties:
        Transactiond:
          $ref: '#/components/schemas/trxid'
        Channel:
          $ref: '#/components/schemas/channel'
        msisdn:
          $ref: '#/components/schemas/msisdn'
        offer:
          type: string
        inactivationReason:
          type: string
      required:
        - Transactiond
        - msisdn
    NotificationBody:
      type: object
      properties:
        subscriptionId:
          $ref:  '#/components/schemas/subscriptionId'
        msisdn:
          $ref: '#/components/schemas/msisdn'
        state:
          $ref: '#/components/schemas/offerState'
        offerId:
          type: string
        offerName:
          type: string
        transactionId:
          $ref: '#/components/schemas/trxid'
        serviceNotificationType:
          $ref: '#/components/schemas/serviceNotificationType'
        serviceId:
          $ref: '#/components/schemas/serviceId'
        serviceName: 
          type: string
        isRenewal:
          type: boolean
        failureReason:
          type: string
        subscriptionStartDate:
          description: 'Date format must be RFC3339'
          type: string
          format: date
        subscriptionEndDate:
          description: 'Date format must be RFC3339'
          type: string
          format: date
        nextChargingDate:
          description: 'Date format must be RFC3339'
          type: string
          format: date
        lastRenewalDate:
          description: 'Date format must be RFC3339'
          type: string
          format: date
        channelType:
          $ref: '#/components/schemas/channel'
        chargingPeriod:
          description: 'Period is in days'
          type: integer
          format: int32
        chagedAmount:
          description: 'local currrency'
          type: integer
          format: int32
        inTrial:
          description: 'It denotes that this trial subscription completed and paid one started' 
          type: boolean
        subscriptionCounter:
          description: | 
            'It denotes the total subscription count and increases each time subscription is created'
          type: integer
          format: int32
        requestDate:
          description: | 
            'Date format must be RFC3339
            It denotes the date of the latest request and changes each time subscription is created'
          type: string
          format: date
      required:
        - msisdn
        - offerId
        - offerName
        - transactionId
        - serviceNotificationType 
    ErrorRsp:
      type: object
      properties:
        code:
          description: 'Enkudo API Error code. See API document descriptions'
          type: string
          maxLength: 8
          pattern: '^[0-9]$'
        errorCode:
          description: 'Enkudo API Error code. See API document descriptions'
          type: string
          maxLength: 8
          pattern: '^[0-9]$'
        message:
          description: 'Human readble ErrorRsp message'
          type: string
          maxLength: 256
      required:
        - code
        - message

#
# COMMON RESPONSES
#
  responses:
    '403':
      description: 'Not Allowed'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorRsp'
    '404':
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorRsp'
    '500':
      description: 'General server error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorRsp'
    default:
      description: Generic Error
