/*
 * Enkudo DSP Northbound Subscription API
 *
 * Enkudo DSP is Telenity’s next-generation digital services platform to monetize the  digital services and content served on top of the customer network. Enkudo DSP solution  enables customers to subscribe/purchase digital content of their choice (ranging from  games, video stream, educational content, etc.) through a mobile application and web  portal with a variety of payment options, on a revenue share business model. This API is for the consumption of Content Providers. It provides end-user subscription,  unsubscription, query information and notification interfaces for DSP.  <br><br> NGSSM's subscription API is inbound, meaning that, for this API, NGSSM acts as the server and request direction is from the client to NGSSM. Subscription APIs include  methods:  - Generate Authcode,  - ReGenerate Authcode,  - Create Subscription and  - Cancel Subscription - Query Subscriber Info   As the names imply, Authcode methods are used to create a one-time password token at OTPS,  Create Subscription is used to create an offer subscription at NGSSM,  whereas Cancel Subscription is used to cancel an existing offer subscription on NGSSM
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "enkudo-dsp-go-server/go"
)

func main() {
	log.Printf("Server started")

	DefaultEnkudoDSPService := openapi.NewDefaultEnkudoDSPService()
	DefaultEnkudoDSPController := openapi.NewDefaultEnkudoDSPController(DefaultEnkudoDSPService)

	router := openapi.NewRouter(DefaultEnkudoDSPController)

	log.Fatal(http.ListenAndServe(":8080", router))

	log.Printf("Terminating")
}
